library(dplyr)
library(tidyr)

git2r::clone("git@github.com:tidyverse/dplyr.git", local_path = "/tmp/dplyr")

data <- gstat_gather_data("/tmp/dplyr")
unique(data[["Author"]])

authorsRemap <- c("Romain François" = "Romain Francois")
data <- gstat_rename_authors(data, authorMap = authorsRemap)

paths <- c("^man", "^docs", "^R/RcppExports.R", "^src/RcppExports.cpp", "*.md$", "inst/valgrind/valgrind.txt$")
data <- gstat_mark_autogenerated_by_path(data, paths)
data <- gstat_add_technology(data)

data %>% filter(!IsAutogenerated) %>% group_by(Author) %>% summarise(Added = sum(Added), Removed = sum(Removed)) %>%
  arrange(desc(Added))
