data <- gstat_gather_data("/home/zzawadz/AllRepos/cdmQMatrix")
data <- gstat_rename_authors(data)
data <- gstat_mark_autogenerated(data)
data <- gstat_add_technology(data)

dataSummary <- data %>% filter(!IsAutogenerated) %>% group_by(Author, Technology) %>% summarise(Added = sum(Added), Removed = sum(Removed))
View(dataSummary)

j_repos <- gh("/users/:username/repos", username = "zzawadz")
allRepos <- vapply(j_repos, "[[", "", "name")

dir.create("~/AllRepos")

library(pbapply)
pblapply(allRepos, function(name) {
  git2r::clone(sprintf("git@github.com:zzawadz/%s.git", name),local_path = file.path("/home/zzawadz/AllRepos",name))
})
