gstat_mark_autogenerated_by_path <- function(data, paths) {
  paths <- c("^man", "^docs", "^R/RcppExports.R", "^src/RcppExports.cpp")
  autogenerated <- rep(FALSE, length(data$FullPath))

  for(p in paths) {
    autogenerated <- autogenerated | grepl(data$FullPath, pattern = p)
  }

  data[["IsAutogenerated"]] <- autogenerated
  data
}
